import { Work_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header/header";
import Footer from "@/components/layout/footer/footer";
import { fetchAllPages } from "@/lib/api";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // Fetch WordPress pages at build time
  const pages = await fetchAllPages().catch(() => []);

  return (
    <html lang="en">
      <body className={`${workSans.variable}`}>
        <Header pages={pages} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
